CREATE TABLE Authors (
	Id TEXT PRIMARY KEY NOT NULL,
   	FullName TEXT NOT NULL
)

CREATE TABLE Books (
	Id TEXT PRIMARY KEY NOT NULL,
   	Title TEXT NOT NULL,
	AuthorId TEXT NULL,
	CreatedAt DateTime2 NOT NULL,
	FOREIGN KEY(Id) REFERENCES Authors(Id)
)

CREATE TABLE AuthorBooks (
	AuthorId TEXT NOT NULL,
	BookId Text NOT NULL,
	FOREIGN KEY(AuthorId) REFERENCES Authors(Id),
	FOREIGN KEY(BookId) REFERENCES Books(Id)
)